In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import sklearn
import sklearn.linear_model
import sklearn.metrics
import matplotlib.pyplot as plt

In [72]:
DATA = "train.csv"
data = pd.read_csv(DATA)
data = data.to_numpy()
data

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [73]:
TEST_DATA = "test.csv"
test_data = pd.read_csv(TEST_DATA)
test_data = test_data.to_numpy()
test_data

array([[892, 3, 'Kelly, Mr. James', ..., 7.8292, nan, 'Q'],
       [893, 3, 'Wilkes, Mrs. James (Ellen Needs)', ..., 7.0, nan, 'S'],
       [894, 2, 'Myles, Mr. Thomas Francis', ..., 9.6875, nan, 'Q'],
       ...,
       [1307, 3, 'Saether, Mr. Simon Sivertsen', ..., 7.25, nan, 'S'],
       [1308, 3, 'Ware, Mr. Frederick', ..., 8.05, nan, 'S'],
       [1309, 3, 'Peter, Master. Michael J', ..., 22.3583, nan, 'C']],
      dtype=object)

In [28]:
np.random.seed(101)
np.random.shuffle(data)
data

array([[214, 0, 2, ..., 13.0, nan, 'S'],
       [767, 0, 1, ..., 39.6, nan, 'C'],
       [590, 0, 3, ..., 8.05, nan, 'S'],
       ...,
       [440, 0, 2, ..., 10.5, nan, 'S'],
       [773, 0, 2, ..., 10.5, 'E77', 'S'],
       [557, 1, 1, ..., 39.6, 'A16', 'C']], dtype=object)

In [76]:
X, y = data[:,0], data[:,1]
print(X.shape)

X = X.reshape((-1,1))
print(X.shape)

X_test, y_test = test_data[:,0], data[:,1]
print(X_test.shape)

def data_split(data):
    return np.split(data, [int(data.shape[0])])

X_train, X_val = data_split(X)
y_train, y_val = data_split(y)
X_test = data_split(X_test)
y_test = data_split(y_test)


(891,)
(891, 1)
(418,)


In [54]:
model = sklearn.linear_model.LinearRegression()
model.fit(X_train.reshape(-1, 1), y_train)

weight = model.coef_
bias = model.intercept_

print(weight)
print(bias)

[-9.46635703e-06]
0.388060379071615


$$b_1=-0.00000947$$
$$b_0=0.39$$
$$\hat Y = b_1X + b_0$$
$$\hat Y = -0.00000947X + 0.39$$

In [44]:
X_train = X_train.reshape(-1,1)
X_val = X_train.reshape(-1,1)
yhat_train = model.predict(X_train)
yhat_val = model.predict(X_val)

In [77]:
print(sklearn.metrics.mean_squared_error(yhat_train, X_test))
print(sklearn.metrics.mean_squared_error(yhat_val, y_test))

ValueError: Found input variables with inconsistent numbers of samples: [891, 2]